
package support;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TimeWSSEI", targetNamespace = "http://sei/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TimeWSSEI {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTimeAsString", targetNamespace = "http://sei/", className = "support.GetTimeAsString")
    @ResponseWrapper(localName = "getTimeAsStringResponse", targetNamespace = "http://sei/", className = "support.GetTimeAsStringResponse")
    @Action(input = "http://sei/TimeWSSEI/getTimeAsStringRequest", output = "http://sei/TimeWSSEI/getTimeAsStringResponse")
    public String getTimeAsString();

}
